name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
         description: Run by cypress command line
         default: yarn cypress run
         
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.7
      
      - name: install dependencies
        run: ${{ github.event.inputs.cli }}

      - name: Run E2E tests
        run: yarn cypress run 

        
      
